### ISSUE TITLE
novaclient auth plugins that are not keystone are deprecated

### ISSUE THREAD

**Issue by clayg** [rackerlabs/rackspace-novaclient#14]
I installed rackspace-novaclient in a fresh virtualenv and get an error trying to run `nova list`

```
ERROR (AttributeError): ImpImporter instance has no attribute 'load_module'
```

More detail:

https://gist.github.com/clayg/b6d924fbca46b2eb8ebf

Probably broke here:

https://github.com/openstack/python-novaclient/commit/88ef0542dc3db5b9b98ae004087e90c123f68ece

**Comment by iangcarroll** [comment]
Running into this issue as well.

**Comment by supermari0** [comment]
This is an upstream bug being fixed by https://review.openstack.org/#/c/262632/

**Comment by 0x91** [comment]
fixed upstream.
