### ISSUE TITLE
stick to novaclient 2.30.2

### ISSUE THREAD

**Issue by kzap** [rackerlabs/rackspace-novaclient#16]
im getting 401s from the rackspace ident when using python-novaclient 3.0+

rackspace-novaclient could stick to novaclient 2.30.2 pls

i outlined my issues here in the supernova repo: https://github.com/major/supernova/issues/110

**Comment by kzap** [comment]
or novaclient 2.30.2 pls, 2.35 has compat issues on some openstack versions

**Comment by hatchetation** [comment]
Thanks @kzap, I was hitting this with python-novaclient==2.27.0, rolling back to 2.30.2 resolved it for me as well

Full error I was seeing (note the null apiKey):

```
$ nova list --debug
REQ: curl -g -i 'https://identity.api.rackspacecloud.com/v2.0/tokens' -X POST -H "Accept: application/json" -H "Content-Type: application/json" -H "User-Agent: python-novaclient" -d '{"auth": {"RAX-KSKEY:apiKeyCredentials": {"username": "fanaticalClient", "apiKey": null}}}'

ERROR (BadRequest): Expecting apiKey (HTTP 400)
```
