### ISSUE TITLE
ERROR (ImportError): No module named openstack.common

### ISSUE THREAD

**Issue by amorphic** [rackerlabs/rackspace-novaclient#17]
As per the [Rackspace official docs](https://support.rackspace.com/how-to/installing-python-novaclient-on-linux-and-mac-os/) I ran the following in a Python 2.7 virtualenv:

```
$ pip install rackspace-novaclient
$ nova image-list
```

This yielded an error:

```
ERROR (ImportError): No module named openstack.common
```

It turns out that the latest version of `python-novaclient` is `4.0.0` and because `rackspace-novaclient` does not place any version contraints on the `python-novaclient` dependency, the latest version is what is installed.

It seems like this one of several issues with more recent versions of `python-novaclient` (#16 mentions a problem with version 3.x).

The `python-novaclient` dependency in `setup.py` should define a "known good" [semantic version](http://semver.org/) range. This would allow the `rackspace-novaclient` maintainers to ensure compatibility with later `python-novaclient` versions before they are included with `rackspace-novaclient`.

**Comment by chrishiestand** [comment]
I'm having the same problem.

```/Users/username/.virtualenvs/rackspace/lib/python2.7/site-packages/novaclient/shell.py:790: UserWarning: novaclient auth plugins that are not keystone are deprecated. Auth plugins should now be done as plugins to keystoneauth and selected with --os-auth-type or OS_AUTH_TYPE
  'novaclient auth plugins that are not keystone are deprecated.'
/Users/username/.virtualenvs/rackspace/lib/python2.7/site-packages/requests/packages/urllib3/connection.py:303: SubjectAltNameWarning: Certificate for identity.api.rackspacecloud.com has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
ERROR (ImportError): No module named openstack.common
```

Could you perhaps cut 1.6 and push to pypi? Apologies if you have a good reason for not doing so.

**Comment by amorphic** [comment]
@chrishiestand if you're looking for a quick fix until the maintainers release a new version of `rackspace-novaclient`:

```
$ pip uninstall python-novaclient
$ pip install python-novaclient==2.35.0
```

**Comment by chrishiestand** [comment]
@amorphic Thanks a lot for the tip. I just did a `git clone` of this repo and a `pip install -e .` from within my virtualenv. It worked great.

**Comment by rgbkrk** [comment]
I'll get a release out, though I'm going to need to find real maintainers from the nova team at Rackspace. I'm leaving Rackspace soon.
